# Changes here will be overwritten by Copier
_commit: v0.4.2
_src_path: gl:openscm/copier-basic-python-repository
email: moeller@iiasa.ac.at
name: Tessa Möller
notebooks: true
package_manager: pixi
project_description_short: Pipeline to handle atoll transect data and combine with
    necessary input data to integrate with BEWARE.
project_url: https://gitlab.com/TessaM97/atoll-paper
